### ISSUE TITLE
EU MEPS Config Change

### ISSUE THREAD

**Issue by sbrendtro** [alephdata/opensanctions#25]
The URL for eu_meps appears to have changed.  Update the URL in config/eu_meps.yml to the following:  http://www.europarl.europa.eu/meps/en/full-list/xml/a

***Updated config/eu_meps.yml***
```
name: eu_meps
description: "[OSANC] Members of the European Parliament"
schedule: weekly
pipeline:
  init:
    method: seed
    params:
      url: 'http://www.europarl.europa.eu/meps/en/full-list/xml/a'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.eu_meps:parse
    handle:
      pass: store
  store:
    method: opensanctions.helpers:store_entity
```
